version: "3.8"

services:
  spring-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: spring-app
    working_dir: /app
    volumes:
      - ./app:/app
    command: ["java", "-jar", "app.jar"]
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    restart: unless-stopped
